### ISSUE TITLE
Windows quoting/commas issue

### ISSUE THREAD

**Issue by andywhite37** [andywhite37/hmm#14]
From #13 -

@jonasmalacofilho - Reporting a small issue found by a colegue (@craice)...

We found a small problem related to missing path quoting: `haxelib run hmm setup` tries to execute `copy /Y C:\HaxeToolkit\haxe\lib\hmm\2,0,1\hmm.cmd C:\HaxeToolkit\haxe\hmm.cmd`, but Windows gets tripped up by the commas and the command fails with `The system cannot find the file specified`.

<details>
<summary>Version information</summary>

```
haxe -version: 3.4.1 (git build development @ 6899468)
neko -version: 2.1.0
on Windows 10 Pro Version 1607 OS Build 14393.1198
```
</details>

**Comment by andywhite37** [comment]
I don't have a windows machine at the moment to test, but one thing to try is to add some quoting in this area.

https://github.com/andywhite37/hmm/blob/master/src/hmm/utils/Shell.hx#L270-L272

**Comment by elsassph** [comment]
Quotes don't help.
