### ISSUE TITLE
Lock haxelib version

### ISSUE THREAD

**Issue by elsassph** [andywhite37/hmm#17]
Would be great to be able to "lock" a haxelib version, eg. if you have haxelibs without version to write the current version in the `hmm.json`

**Comment by andywhite37** [comment]
Yeah, that is a good idea.

Maybe something like this:

`hmm lock` - attempts to lock all libraries
`hmm lock lib1 lib2 ...` - attempts to lock specified libraries

Any thoughts on whether `lock` should do anything for git/hg-based dependencies?  One thought would be to `git rev-parse --short HEAD` to get the current commit you're pointing at, and write that to the hmm.json as the `ref`?  That would only help if your `ref` was a branch name (like if you were pointing at a master branch, and wanted to lock onto a specific commit instead).

**Comment by elsassph** [comment]
The lock one/all syntax is exactly what I had in mind.

Locking a git/hg report to a specific commit hash or tag would be nifty: edit locally, commit, lock to write the commit hash in the JSON.

**Comment by elsassph** [comment]
I actually already have the lock version for haxelib working here - I'll try to share that soon.

**Comment by andywhite37** [comment]
awesome, sounds good

**Comment by elsassph** [comment]
That was fun to do - no idea if the Mercurial ref is correct.

**Comment by elsassph** [comment]
Feature was added \o/
