### ISSUE TITLE
read libraries from HXML

### ISSUE THREAD

**Issue by fponticelli** [andywhite37/hmm#2]
It would be nice to have something like the following:

``` sh
haxelib run hmm init build.hxml
```

That will create a `hmm.json` with the libraries defined in `build.hxml` and possibly their current versions.

Also an `update` command could be useful.

**Comment by ghost** [comment]
good idea

**Comment by ghost** [comment]
How about a `hmm from-hxml build.hxml something.hxml ...` command that reads libs from an hxml and adds them.

And a `hmm to-hxml` that dumps all the libs like:

```
-lib lib1
-lib lib2
```

**Comment by andywhite37** [comment]
This is available now in 1.2.0

Do `hmm hmm-update` to get the latest
