### ISSUE TITLE
--quiet?

### ISSUE THREAD

**Issue by ninjamuffin99** [andywhite37/hmm#20]
when running `hmm install` in something like a github action, it's a bit unpleasant to have pages upon pages of download progress!!

![image](https://github.com/andywhite37/hmm/assets/22229331/7f06f533-68b2-4b41-a3eb-daa3f6a01fea)

something to pass through the haxelib --quiet flag for installation?

https://lib.haxe.org/documentation/using-haxelib/#quiet

**Comment by andywhite37** [comment]
That seems like a very good idea. If you are willing to give it a shot, I would be happy to accept a pull request. I can probably do this at some point too, but I have some other things going on, so I'm not sure when I'll get around to it. If you submit a PR before I can get to this, I will commit to building it and releasing a new version.

I checked the code, and I think it could be as simple as injecting something here: 

https://github.com/andywhite37/hmm/blob/master/src/hmm/utils/Shell.hx#L143

Maybe we can read that arg in the `main` entrypoint and pass it down, or statically set it in the `Shell`.

https://github.com/andywhite37/hmm/blob/master/src/hmm/Hmm.hx#L39-L41

I don't remember exactly how all this works.

**Comment by ninjamuffin99** [comment]
haha thanks for getting back to me its all good. I will poke around today,
thanks for leading me the right way!

**Comment by andywhite37** [comment]
This has been released in 3.1.0 - let me know if there are any problems, and we can re-open this.
