### ISSUE TITLE
Ctrl-C during hmm install only kills the current haxelib task, not the entire process

### ISSUE THREAD

**Issue by ghost** [andywhite37/hmm#8]
I think because haxe's Sys call redirects stdin to the child process.

**Comment by andywhite37** [comment]
This might work now, because if you ctrl-c the sys command, it probably exits with a non-zero code, which now causes hmm to exit (as of 1.4.0).  Need to check.

**Comment by andywhite37** [comment]
Confirmed that ctrl-c'ing a haxelib task causes it to exit with status 512
